### ISSUE TITLE
Consider how to handle failed cherry-picks

### ISSUE THREAD

**Issue by ncoghlan** [Mariatta/chic_a_cherry_picker#15]
I think this utility has a lot of potential to evolve into the bot that actually *does* the automated cherry-pick PR creation, and one of the things we'll need to address there is what to do when the routine cherry pick fails.

At the moment, if the first cherry-pick fails, it leaves the checkout in a messy state, so all the subsequent branch creation commands fail.

I'm thinking one way of tackling this would be to:

1. Complain and exit early if the checkout is in a messy state, and suggesting running `git stash` to move the local changes aside.
2. If any of the cherry-picks fail do an immediate `git reset --hard` and move on to the next branch.

Does that approach sound reasonable?

**Comment by Mariatta** [comment]
Thanks for using (and improving) this script :)
I don't yet know how to write a bot.. :( I'll need some more guidance for it.
It also sounds like Berker and/or Maciej are already working on the bot, I don't really want to step on their toes.

Sounds reasonable. In some situations where the merge failed, I've been able to do `git cherry-pick --abort`.

**Comment by Mariatta** [comment]
This issue was moved to python/core-workflow#45
